from app import db

class User(db.Model):
    __tablename__ = 'usuario'
    cod_usuario = db.Column(db.Integer, primary_key=True)
    nom_usuario = db.Column(db.String, unique=True, nullable=False)
    senha = db.Column(db.String(32), nullable=False)
    login = db.Column(db.String(20), unique=True, nullable=False)
    status = db.Column(db.String(1), nullable=False, default='A')
    cod_tipo_usuario = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return f'<User {self.login}>'
    

class BPAHeader(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    year_month = db.Column(db.String(6), nullable=False)
    total_lines = db.Column(db.Integer, default=1)
    total_sheets = db.Column(db.Integer, default=1)
    org_name = db.Column(db.String(30), nullable=False)
    org_acronym = db.Column(db.String(6))
    cgc_cpf = db.Column(db.String(14), nullable=False)
    dest_name = db.Column(db.String(40), nullable=False)
    dest_type = db.Column(db.String(1), nullable=False)
    version = db.Column(db.String(10), default='1.0.0')

class BPAConsolidado(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    cnes = db.Column(db.String(7), nullable=False)
    competencia = db.Column(db.String(6), nullable=False)
    cbo = db.Column(db.String(6), nullable=False)
    folha = db.Column(db.Integer, nullable=False)
    sequencial = db.Column(db.Integer, nullable=False)
    procedimento = db.Column(db.String(10), nullable=False)
    idade = db.Column(db.Integer, nullable=False)
    quantidade = db.Column(db.Integer, nullable=False)
    origem = db.Column(db.String(3), default='EXT')

class BPAIndividualizado(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    cnes = db.Column(db.String(7), nullable=False)
    competencia = db.Column(db.String(6), nullable=False)
    cns_profissional = db.Column(db.String(15), nullable=False)
    cbo = db.Column(db.String(6), nullable=False)
    data_atendimento = db.Column(db.Date, nullable=False)
    folha = db.Column(db.Integer, nullable=False)
    sequencial = db.Column(db.Integer, nullable=False)
    procedimento = db.Column(db.String(10), nullable=False)
    cns_paciente = db.Column(db.String(15), nullable=False)
    sexo = db.Column(db.String(1), nullable=False)
    codigo_municipio = db.Column(db.String(6), nullable=False)
    cid = db.Column(db.String(4), nullable=False)
    idade = db.Column(db.Integer, nullable=False)
    quantidade = db.Column(db.Integer, nullable=False)
    carater_atendimento = db.Column(db.String(2), default='01')
    numero_autorizacao = db.Column(db.String(13))
    nome_paciente = db.Column(db.String(30), nullable=False)
    data_nascimento = db.Column(db.Date, nullable=False)
    raca = db.Column(db.String(2), default='01')
    etnia = db.Column(db.String(4))
    nacionalidade = db.Column(db.String(3), default='010')
    servico = db.Column(db.String(3))
    classificacao = db.Column(db.String(3))
    equipe_seq = db.Column(db.String(8))
    equipe_area = db.Column(db.String(4))
    cnpj = db.Column(db.String(14))
    cep = db.Column(db.String(8))
    codigo_logradouro = db.Column(db.String(3))
    endereco = db.Column(db.String(30))
    complemento = db.Column(db.String(10))
    numero = db.Column(db.String(5))
    bairro = db.Column(db.String(30))
    telefone = db.Column(db.String(11))
    email = db.Column(db.String(40))
    ine = db.Column(db.String(10))
